/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.34
 * Generated at: 2025-03-30 21:56:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import model.Contato;
import dao.ContatoDAO;
import java.util.List;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("model.Contato");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("dao.ContatoDAO");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    // Check if user is logged in
    if (session.getAttribute("usuario") == null) {
        response.sendRedirect("login.jsp");
        return;
    }
    
    String action = request.getParameter("action");
    if (action == null) action = "listar";
    
    ContatoDAO contatoDAO = new ContatoDAO();

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Lista de Contatos</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div>\r\n");
      out.write("        <h1>Lista de Contatos</h1>\r\n");
      out.write("        <div>\r\n");
      out.write("                <a href=\"cadastrar.jsp\" class=\"btn btn-primary\">Novo Contato</a>\r\n");
      out.write("                <a href=\"home.jsp?action=listar\" class=\"btn btn-secondary\">Listar por Nome</a>\r\n");
      out.write("                <a href=\"home.jsp?action=listarPorEstado\" class=\"btn btn-secondary\">Listar por Estado</a>\r\n");
      out.write("                <a href=\"logout.jsp\" class=\"btn btn-danger\">Sair</a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"search-form\">\r\n");
      out.write("            <div class=\"card\">\r\n");
      out.write("                <form action=\"home.jsp\" method=\"get\" class=\"form-group\">\r\n");
      out.write("                    <input type=\"hidden\" name=\"action\" value=\"buscarPorNome\">\r\n");
      out.write("                    <input type=\"text\" name=\"nome\" class=\"form-control\" placeholder=\"Buscar por primeiro nome\" required>\r\n");
      out.write("                    <button type=\"submit\" class=\"btn btn-primary\">Buscar</button>\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"card\">\r\n");
      out.write("                <form action=\"home.jsp\" method=\"get\" class=\"form-group\">\r\n");
      out.write("                    <input type=\"hidden\" name=\"action\" value=\"buscarPorMes\">\r\n");
      out.write("                    <select name=\"mes\" class=\"form-control\" required>\r\n");
      out.write("                        <option value=\"\">Selecione o mês</option>\r\n");
      out.write("                        ");
 for(int i = 1; i <= 12; i++) { 
      out.write("\r\n");
      out.write("                            <option value=\"");
      out.print( i );
      out.write('"');
      out.write('>');
      out.print( i );
      out.write("</option>\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("                    </select>\r\n");
      out.write("                    <button type=\"submit\" class=\"btn btn-primary\">Buscar Aniversariantes</button>\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"table-container\">\r\n");
      out.write("            ");
 if(action.equals("listar")) { 
      out.write("\r\n");
      out.write("                <table class=\"table\">\r\n");
      out.write("                    <thead>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <th>CPF</th>\r\n");
      out.write("                            <th>Nome</th>\r\n");
      out.write("                            <th>DDD</th>\r\n");
      out.write("                            <th>Celular</th>\r\n");
      out.write("                            <th>Email</th>\r\n");
      out.write("                            <th>Mês Nasc.</th>\r\n");
      out.write("                            <th>Ações</th>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    </thead>\r\n");
      out.write("                    <tbody>\r\n");
      out.write("                        ");
 for(Contato contato : contatoDAO.listarTodos()) { 
      out.write("\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td>");
      out.print( contato.getCpf() );
      out.write("</td>\r\n");
      out.write("                                <td>");
      out.print( contato.getPrimeiroNome() );
      out.write("</td>\r\n");
      out.write("                                <td>");
      out.print( contato.getDdd() );
      out.write("</td>\r\n");
      out.write("                                <td>");
      out.print( contato.getCelular() );
      out.write("</td>\r\n");
      out.write("                                <td>");
      out.print( contato.getEmail() );
      out.write("</td>\r\n");
      out.write("                                <td>");
      out.print( contato.getMesNascimento() );
      out.write("</td>\r\n");
      out.write("                                <td>\r\n");
      out.write("                                    <a href=\"editar.jsp?cpf=");
      out.print( contato.getCpf() );
      out.write("\" class=\"btn btn-secondary\">Editar</a>\r\n");
      out.write("                                    <a href=\"excluir.jsp?cpf=");
      out.print( contato.getCpf() );
      out.write("\" class=\"btn btn-danger\" onclick=\"return confirm('Confirma a exclusão?')\">Excluir</a>\r\n");
      out.write("                                </td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("                    </tbody>\r\n");
      out.write("                </table>\r\n");
      out.write("            ");
 } else if(action.equals("listarPorEstado")) { 
      out.write("\r\n");
      out.write("                <table class=\"table\">\r\n");
      out.write("                    <thead>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <th>ID</th>\r\n");
      out.write("                            <th>Nome</th>\r\n");
      out.write("                            <th>Endereço</th>\r\n");
      out.write("                            <th>Cidade</th>\r\n");
      out.write("                            <th>Email</th>\r\n");
      out.write("                            <th>Ações</th>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    </thead>\r\n");
      out.write("                    <tbody>\r\n");
      out.write("                        ");
 for(Contato contato : contatoDAO.listarPorEstado()) { 
      out.write("\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td>");
      out.print( contato.getId() );
      out.write("</td>\r\n");
      out.write("                                <td>");
      out.print( contato.getPrimeiroNome() );
      out.write("</td>\r\n");
      out.write("                                <td>");
      out.print( contato.getEndereco() );
      out.write("</td>\r\n");
      out.write("                                <td>");
      out.print( contato.getCidade() );
      out.write("</td>\r\n");
      out.write("                                <td>");
      out.print( contato.getEmail() );
      out.write("</td>\r\n");
      out.write("                                <td>\r\n");
      out.write("                                    <a href=\"editar.jsp?cpf=");
      out.print( contato.getCpf() );
      out.write("\" class=\"btn btn-secondary\">Editar</a>\r\n");
      out.write("                                    <a href=\"excluir.jsp?cpf=");
      out.print( contato.getCpf() );
      out.write("\" class=\"btn btn-danger\" onclick=\"return confirm('Confirma a exclusão?')\">Excluir</a>\r\n");
      out.write("                                </td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                        ");
 } 
      out.write("\r\n");
      out.write("                    </tbody>\r\n");
      out.write("                </table>\r\n");
      out.write("            ");
 } else if(action.equals("buscarPorNome")) { 
                String nome = request.getParameter("nome");
                Contato contato = contatoDAO.buscarPorPrimeiroNome(nome);
                if(contato != null) { 
      out.write("\r\n");
      out.write("                    <table class=\"table\">\r\n");
      out.write("                        <thead>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <th>Endereço</th>\r\n");
      out.write("                                <th>Cidade</th>\r\n");
      out.write("                                <th>DDD</th>\r\n");
      out.write("                                <th>Celular</th>\r\n");
      out.write("                                <th>Email</th>\r\n");
      out.write("                                <th>CPF</th>\r\n");
      out.write("                                <th>Ações</th>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                        </thead>\r\n");
      out.write("                        <tbody>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <td>");
      out.print( contato.getEndereco() );
      out.write("</td>\r\n");
      out.write("                                <td>");
      out.print( contato.getCidade() );
      out.write("</td>\r\n");
      out.write("                                <td>");
      out.print( contato.getDdd() );
      out.write("</td>\r\n");
      out.write("                                <td>");
      out.print( contato.getCelular() );
      out.write("</td>\r\n");
      out.write("                                <td>");
      out.print( contato.getEmail() );
      out.write("</td>\r\n");
      out.write("                                <td>");
      out.print( contato.getCpf() );
      out.write("</td>\r\n");
      out.write("                                <td>\r\n");
      out.write("                                    <a href=\"editar.jsp?cpf=");
      out.print( contato.getCpf() );
      out.write("\" class=\"btn btn-secondary\">Editar</a>\r\n");
      out.write("                                    <a href=\"excluir.jsp?cpf=");
      out.print( contato.getCpf() );
      out.write("\" class=\"btn btn-danger\" onclick=\"return confirm('Confirma a exclusão?')\">Excluir</a>\r\n");
      out.write("                                </td>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                        </tbody>\r\n");
      out.write("                    </table>\r\n");
      out.write("                ");
 } else { 
      out.write("\r\n");
      out.write("                    <p>Nenhum contato encontrado com o nome ");
      out.print( nome );
      out.write(".</p>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("            ");
 } else if(action.equals("buscarPorMes")) { 
                int mes = Integer.parseInt(request.getParameter("mes"));
                List<Contato> contatos = contatoDAO.buscarPorMesAniversario(mes);
                if(!contatos.isEmpty()) { 
      out.write("\r\n");
      out.write("                    <table class=\"table\">\r\n");
      out.write("                        <thead>\r\n");
      out.write("                            <tr>\r\n");
      out.write("                                <th>Nome</th>\r\n");
      out.write("                                <th>Sobrenome</th>\r\n");
      out.write("                                <th>Endereço</th>\r\n");
      out.write("                                <th>Cidade</th>\r\n");
      out.write("                                <th>Estado</th>\r\n");
      out.write("                                <th>DDD</th>\r\n");
      out.write("                                <th>Celular</th>\r\n");
      out.write("                                <th>Email</th>\r\n");
      out.write("                                <th>CPF</th>\r\n");
      out.write("                                <th>Ações</th>\r\n");
      out.write("                            </tr>\r\n");
      out.write("                        </thead>\r\n");
      out.write("                        <tbody>\r\n");
      out.write("                            ");
 for(Contato contato : contatos) { 
      out.write("\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <td>");
      out.print( contato.getPrimeiroNome() );
      out.write("</td>\r\n");
      out.write("                                    <td>");
      out.print( contato.getUltimoNome() );
      out.write("</td>\r\n");
      out.write("                                    <td>");
      out.print( contato.getEndereco() );
      out.write("</td>\r\n");
      out.write("                                    <td>");
      out.print( contato.getCidade() );
      out.write("</td>\r\n");
      out.write("                                    <td>");
      out.print( contato.getEstado() );
      out.write("</td>\r\n");
      out.write("                                    <td>");
      out.print( contato.getDdd() );
      out.write("</td>\r\n");
      out.write("                                    <td>");
      out.print( contato.getCelular() );
      out.write("</td>\r\n");
      out.write("                                    <td>");
      out.print( contato.getEmail() );
      out.write("</td>\r\n");
      out.write("                                    <td>");
      out.print( contato.getCpf() );
      out.write("</td>\r\n");
      out.write("                                    <td>\r\n");
      out.write("                                        <a href=\"editar.jsp?cpf=");
      out.print( contato.getCpf() );
      out.write("\" class=\"btn btn-secondary\">Editar</a>\r\n");
      out.write("                                        <a href=\"excluir.jsp?cpf=");
      out.print( contato.getCpf() );
      out.write("\" class=\"btn btn-danger\" onclick=\"return confirm('Confirma a exclusão?')\">Excluir</a>\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                            ");
 } 
      out.write("\r\n");
      out.write("                        </tbody>\r\n");
      out.write("                    </table>\r\n");
      out.write("                ");
 } else { 
      out.write("\r\n");
      out.write("                    <p>Nenhum contato encontrado para o mês ");
      out.print( mes );
      out.write(".</p>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
